<?php
/*
 * Created on Dec 26, 2013
 *
 * To change the template for this generated file go to
 * Window - Preferences - PHPeclipse - PHP - Code Templates
 */
 //$cuki_dm is the root domain of server without 'http://' prefix
 //$domain is the subdomain of this program

$cuki_dm=$_SERVER['SERVER_NAME'];
$domain ='http://'.$cuki_dm.'/bk';
#$activate_domin=$domain.'/admin/activate.php';

#$detail_domain=$domain.'/details.php';
#$suggest_domain=$domain.'/admin/suggestion.php';
#$registe_domain=$domain.'/registe.php';

$string = '<?php'."\n".
			'//This file is generated by setup.php'."\n"
			.'$cuki_dm="'.$_SERVER['SERVER_NAME'].'";'."\n"
			.'$domain="'.'http://'.$cuki_dm.'/bk'.'";'."\n"
			.'$activate_domin="'.$domain.'/admin/activate.php'.'";'."\n"
			.'$detail_domain="'.$domain.'/details.php'.'";'."\n"
			.'$suggest_domain="'.$domain.'/admin/suggestion.php'.'";'."\n"
			.'$registe_domain="'.$domain.'/registe.php'.'";'."\n".'?>';

$filename = 'include/lib/domain.inc';
try{
	file_put_contents($filename,$string);
	echo 'Your configuration file has saved!';
	readfile($filename);
}
catch(Exception $name){
	echo $name;
}
?>
